# Generated by Django 4.2.16 on 2026-06-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('category', models.CharField(choices=[('tech', 'Tecnología'), ('home', 'Hogar'), ('books', 'Libros'), ('toys', 'Juguetes')], default='tech', max_length=20, verbose_name='categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
